### ISSUE TITLE
Add official maintainers

### ISSUE THREAD

**Issue by einenlum** [KnpLabs/muse#9]
@gquemener Would you be ok to become an official maintainer of the project in the Readme?
Maybe @Shivoham would be interested too?

**Comment by gquemener** [comment]
Yup, no problem with me 👍 
I would need admin rights, though 😉

**Comment by gquemener** [comment]
Hey !

What about this @PedroTroller @polc @NiR- @lwagner ?

**Comment by akerouanton** [comment]
Hey @gquemener, I hope you're doing well :slightly_smiling_face: We can indeed give you admin rights if you're still interested into maintaining this repo.

**Comment by gquemener** [comment]
Hello @NiR- :wave: 

I am doing well, thank you (and wish you the same!).

Yep, I'm still interested in this great opportunity! ^^

Cheers :hand:

**Comment by akerouanton** [comment]
It's hackathon time so yeah I'm doing well too :stuck_out_tongue: I gave you admin rights, so i'm closing this issue :wink:

**Comment by gquemener** [comment]
:tada: Thanks :+1:

**Comment by gquemener** [comment]
![](https://66.media.tumblr.com/3ebd1c709e82ec5f8e7901266a8ffa3d/tumblr_n0weweX8wY1qi1iomo1_400.gif)

Enjoy!
